### ISSUE TITLE
Debian and build system

### ISSUE THREAD

**Issue by toobaz** [kwgoodman/bottleneck#114]
I would like to create a Debian package for bottleneck.

Since (according to the Debian policy) I need to regenerate the ``*.c`` files in the build process (rather than using the ones shipped in the tarball), and since I want to deviate as least as possible from the upstream build process, it is my understanding that I should run first each ``*_setup.py`` inside ``bottleneck/scr/auto_pyx`` (and then the main ``setup.py``). However:

```
~/bottleneck-1.0.0$ cd bottleneck/src/auto_pyx/
~/bottleneck-1.0.0/bottleneck/src/auto_pyx$ python\
nonreduce_setup.py build_ext --inplace
running build_ext
cythoning nonreduce.pyx to nonreduce.c
error: [Errno 2] No such file or directory: '/home/pietro/bottleneck-
1.0.0/bottleneck/src/auto_pyx/nonreduce.pyx'
```

Indeed, the ``*.pyx`` files are in ``templates``. What is the intended use of the ``*_setup.py`` files?

**Comment by kwgoodman** [comment]
Getting Bottleneck into Debian would be great!

The auto-generated C files are a pain in the ass. They are large which makes `git diff` painful and bloats the size of the tarball. And they are a security risk because someone (me) could slip in some code during a pull request. Also if someone commits a change to a pyx file without updating the C files then our newly set up CI, which runs off of the C files, will not unit test the change.

So I am interested in pulling out the auto-generated C files and instead have the top-level setup.py construct them at install time. I think that's what pandas does. If anyone is interested in working on that, let me know. The downside, of course, is that installing bottleneck would now require cython. And that I only test with one version of cython.

I never use the auto-gen C files in the repo. I always regenerate with `make all`. So to answer your question on how to generate the C files with the current release (1.0), take a look at the top-level makefile.

Let me know if you run into any problems.

**Comment by toobaz** [comment]
Yes, pandas (and most other packages I can think of) generates the *.c files in the top-level ``setup.py``. This can actually be [very simple to do](http://pietrobattiston.it/gitweb?p=jsaone.git;a=blob;f=setup.py;h=777a484e37999ceaaa25e5718cadff5393bfa095;hb=HEAD#l17).

By the way, pandas does ship C files in the releases, but does not keep them in git - they are generated at release time. And it's also simple to write a ``setup.py`` which will generate them if Cython is installed and otherwise use the shipped ones.

So if you like this approach I can provide a PR (also restructuring a bit the organization in folders, I guess?).

**Comment by kwgoodman** [comment]
A PR would be great! What restructuring of the folders do you have in mind?

**Comment by toobaz** [comment]
Well... I fail to see the utility/sense of having the .pyx (and generated .c) files in ``bottleneck/src/auto_pyx/`` rather than in ``bottleneck/``, since that's where the ``.so`` finally end up (most projects keep the Cython sources in the same folder as final binaries).

**Comment by kwgoodman** [comment]
OK, so auto generated .pyx and .c go to bottleneck/bottleneck and are gitignored. I guess we'd also move reduce_setup.py, nonreduce_setup.py, etc to bottleneck/bottleneck.

If we additionally moved csrc into template then we can delete the auto_pyx directory. Which would allow us to remove the src directory and replace it with the template directory.

Does that agree with what you are thinking? That's a lot of rewiring. If it is too much then I can make a commit that moves things around before you start.

**Comment by kwgoodman** [comment]
Thank you for our new, modern installation system! Let us know if you run into any issues getting bottleneck into debian. I'll close.
