### ISSUE TITLE
How can I compile once instead of twice?

### ISSUE THREAD

**Issue by kwgoodman** [kwgoodman/bottleneck#134]
In the c_rewrite branch slow.c in compiled twice since it is used by both the reduce and move modules. How can I compile it only once?

setup.py:
```
    ext_list = [Extension("bottleneck.reduce2",
                          sources=["bottleneck/src/reduce2.c",
                                   "bottleneck/src/slow.c"],
                          include_dirs=[np.get_include()],
                          extra_compile_args=['-O2'])]
    ext_list += [Extension("bottleneck.move2",
                           sources=["bottleneck/src/move2.c",
                                    "bottleneck/src/slow.c"],
                           include_dirs=[np.get_include()],
                           extra_compile_args=['-O2'])]
```

**Comment by Midnighter** [comment]
Probably because changes to sources are tracked per extension? (See also [this SO question](https://stackoverflow.com/questions/35088717/compile-python-extensions-with-common-c-cpp-files-how-to-avoid-recompilation-o) without helpful answers :disappointed: .)  I'm not sure how you want to organize the structure of the package but I suggest either creating one "library" extension that contains all the functionality or actually compile a shared library and expose parts of it via Cython.

**Comment by kwgoodman** [comment]
Too bad there is no simple python solution.

I think using cython would add more problems than it solves. 

I could move the one function in slow.c to slow.h. That would remove slow from setup.py and remove all the output caused by compiling slow four times.
