### ISSUE TITLE
upcasting/downcasting

### ISSUE THREAD

**Issue by dineshbvadhia** [kwgoodman/bottleneck#152]
bottleneck.argpartsort(arr, int n, axis=-1)

After many years of use, just noticed this: On 64-bit systems, I typically use 32-bit data structures. A argpartsort on a 32-bit numpy array returned 64-bit integers.

Should the results be of the same cast as the data object being argpartsort'ed?

**Comment by kwgoodman** [comment]
It's nice to hear from a long-time user.

Certainly partsort (which will be called partition in bn 1.2) should return the same dtype as the input array. It just reorders the array elements.

For argpartsort (to be called argpartition) it is not so clear. Instead of returning a sorted copy of the input array it returns the indices. The dtype of the indices is np.intp which on your system is int64.

I should add the return type to the docstring.

**Comment by dineshbvadhia** [comment]
Bottleneck is fabulous - should be a standard part of numpy/scipy.

Ah, I see what you mean about argpartsort - if arr is the array then you can't rely on its dtype because it could be anything eg. float32/64 or int32/64.
