### ISSUE TITLE
Relaxed stride checking in numpy 1.12 causes bottleneck unit test failures

### ISSUE THREAD

**Issue by fmaussion** [kwgoodman/bottleneck#161]
Hi, this is what reproduces the problem on my machine (linux mint):

```python
In [1]: import numpy as np

In [2]: import bottleneck as bn

In [3]: print('numpy:', np.__version__)
numpy: 1.12.0

In [4]: print('bottleneck:', bn.__version__)
bottleneck: 1.2.0

In [5]: a = np.ones((3, 2))

In [6]: np.sum(a[:, [1]]), bn.nansum(a[:, [1]])
Out[6]: (3.0, 1.0)

In [7]: np.sum(a[:, [1]].copy()), bn.nansum(a[:, [1]].copy())
Out[7]: (3.0, 3.0)
```

This has been hitting the [xarray test suite on debian](https://github.com/pydata/xarray/issues/1208). 

Thanks!

**Comment by kwgoodman** [comment]
It works fine with numpy 1.11 which is what bottleneck 1.2 supports. So my guess is that you are using numpy 1.12. My second guess is that the unit test failures with numpy 1.12 is due to the change in numpy's relaxed stride checking. My third guess is that I don't understand what relaxed stride checking is. (That last one is not a guess.)

I've added your example as a unit test.

**Comment by kwgoodman** [comment]
OK, I made the fix in master.

**Comment by fmaussion** [comment]
That was fast! Thanks a lot.

**Comment by kwgoodman** [comment]
Well, you rang the fire alarm. Thanks for reporting and thanks for a simple example.

**Comment by shoyer** [comment]
Consider issuing a bug fix release including this fix? I don't think it break any NumPy 1.11 users...

**Comment by kwgoodman** [comment]
A bug in numpy 1.12.0 prevented me from making a bug fix release. But it should be possible now that 1.12.1 is out.

Ugh. The current blocker is here: #166.

**Comment by kwgoodman** [comment]
See #168
